### ISSUE TITLE
Práctica de Hilos

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-de-hilos-Anthony4523#2]
[Práctica de hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Anthony4523/files/6499440/Practica.de.hilos.pdf)

**Comment by CxrlosMX** [comment]
Practica muy bien detallada, buen trabajo 
Porcentaje obtenido: 20%

**Comment by josealfredo79** [comment]
Revisado y bien hecho.
